import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Andrew Tao</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Hi! <br/> My name is Andrew <br/>
        </h1> &nbsp;&nbsp;

        <span>
          <Image src="/Prof2.jpg" alt="Headshot" width={200} height={300} />
        </span>

        <p className={styles.description}>
          Find me at the following locations <br/>
          <a href="https://github.com/Andrewtsy">
            Github
          </a> &nbsp;
          <a href="https://www.linkedin.com/in/andrew-tao-5a9729213/">
            Linkedin
          </a> &nbsp;
          <a href="https://www.instagram.com/andrew.tao1/">
            Instagram
          </a>
        </p>
      </main>
    </div>
  )
}
